# Generated by Django 5.1.5 on 2025-02-11 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("original", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
